package aoc2024

import (
	"testing"

	"github.com/hierynomus/code-challenges/adventofcode/pkg/day"
)

const A2024D08Sample = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

func TestDay08_Sample(t *testing.T) {
	d := day.TestDay(t, Day08)
	d.WithInput(A2024D08Sample, "14", "34")
}
